apiVersion: v1
kind: Service
metadata:
  name: kubeconfig-generator
  labels:
    app: kubeconfig-generator
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: kubeconfig-generator
